import type { Building, Technology } from '../schemas/game';

export const INITIAL_BUILDINGS: Building[] = [
  {
    id: 'colony-core-001',
    name: 'Colony Core',
    type: 'COMMAND',
    category: 'COMMAND',
    level: 1,
    production: { ENERGY: 2 },
    cost: { METAL: 0 },
    description: 'Autonomous command spine for the first planetary outpost.',
    automation: 1,
    maxHealth: 1000,
    currentHealth: 1000,
  },
  {
    id: 'solar-hub-001',
    name: 'Solar Hub',
    type: 'ENERGY_GENERATOR',
    category: 'PRODUCTION',
    level: 1,
    production: { ENERGY: 10 },
    cost: { METAL: 50 },
    description: 'Basic energy generation using orbital solar arrays.',
  },
  {
    id: 'mining-station-001',
    name: 'Mining Station',
    type: 'METAL_EXTRACTOR',
    category: 'PRODUCTION',
    level: 1,
    production: { METAL: 5 },
    consumption: { ENERGY: 2 },
    cost: { METAL: 100, ENERGY: 20 },
    description: 'Extracts metal from the planet surface using one mining drone.',
    automation: 1,
  },
];

export const BUILDING_TEMPLATES: Omit<Building, 'id'>[] = [
  {
    name: 'Solar Hub',
    type: 'ENERGY_GENERATOR',
    category: 'PRODUCTION',
    level: 1,
    production: { ENERGY: 10 },
    cost: { METAL: 50 },
    description: 'Basic energy generation using solar arrays.',
  },
  {
    name: 'Mining Station',
    type: 'METAL_EXTRACTOR',
    category: 'PRODUCTION',
    level: 1,
    production: { METAL: 5 },
    consumption: { ENERGY: 2 },
    cost: { METAL: 100, ENERGY: 20 },
    description: 'Extracts metal from the planet surface.',
    automation: 1,
  },
  {
    name: 'Drone Factory',
    type: 'DRONE_FACTORY',
    category: 'PRODUCTION',
    level: 1,
    production: { METAL: 3 },
    consumption: { ENERGY: 6, GAS: 1 },
    cost: { METAL: 260, CRYSTAL: 40, ENERGY: 120 },
    description: 'Builds autonomous mining and defense drones for idle automation.',
    automation: 3,
  },
  {
    name: 'Storage Core',
    type: 'STORAGE',
    category: 'STORAGE',
    level: 1,
    cost: { METAL: 180, CRYSTAL: 25 },
    description: 'Compresses local colony snapshots and increases safe stockpiles.',
  },
  {
    name: 'Defense Turret',
    type: 'DEFENSE',
    category: 'DEFENSE',
    level: 1,
    consumption: { ENERGY: 3 },
    cost: { METAL: 220, ENERGY: 80 },
    description: 'Automated plasma turret that mitigates pirate and alien raids.',
    defense: 18,
  },
  {
    name: 'Quantum Reactor',
    type: 'ADVANCED_POWER',
    category: 'PRODUCTION',
    level: 1,
    production: { ENERGY: 55, QUANTUM_DUST: 0.2 },
    consumption: { CRYSTAL: 0.5 },
    cost: { METAL: 900, CRYSTAL: 260, DARK_MATTER: 5 },
    description: 'Advanced reactor that unlocks deep-space infrastructure.',
  },
  {
    name: 'Nano Lab',
    type: 'RESEARCH',
    category: 'RESEARCH',
    level: 1,
    production: { QUANTUM_DUST: 0.5 },
    consumption: { ENERGY: 12, CRYSTAL: 1 },
    cost: { METAL: 520, CRYSTAL: 180, GAS: 80 },
    description: 'Offline AI-safe research lab for dynamic technology discovery.',
  },
  {
    name: 'Wormhole Gate',
    type: 'TRAVEL',
    category: 'UTILITY',
    level: 1,
    consumption: { ENERGY: 25, DARK_MATTER: 0.1 },
    cost: { METAL: 1200, CRYSTAL: 450, DARK_MATTER: 25 },
    description: 'Projects a local-sector bridge for P2P galaxy travel and trade.',
  },
  {
    name: 'Orbital Cannon',
    type: 'DEFENSE',
    category: 'DEFENSE',
    level: 1,
    consumption: { ENERGY: 18 },
    cost: { METAL: 1000, CRYSTAL: 220, QUANTUM_DUST: 30 },
    description: 'High-orbit weapon platform for cooperative defense events.',
    defense: 75,
  },
  {
    name: 'AI Core Nexus',
    type: 'AI_CORE',
    category: 'COMMAND',
    level: 1,
    production: { QUANTUM_DUST: 1 },
    consumption: { ENERGY: 30 },
    cost: { METAL: 1500, CRYSTAL: 550, QUANTUM_DUST: 60 },
    description: 'Local WebLLM governance node that proposes safe JSON evolution patches.',
    automation: 8,
  },
  // New Military/Science Buildings
  {
    name: 'Xeno-Biology Wing',
    type: 'SCIENCE_EXTRACTOR',
    category: 'RESEARCH',
    level: 1,
    production: { ALIEN_BIOMASS: 0.3 },
    consumption: { ENERGY: 15, METAL: 5 },
    cost: { METAL: 600, CRYSTAL: 300, GAS: 100 },
    description: 'Studies alien lifeforms to advance esoteric technologies.',
  },
  {
    name: 'Plasma Foundry',
    type: 'MILITARY_PRODUCTION',
    category: 'PRODUCTION',
    level: 1,
    production: { METAL: 2 },
    consumption: { ENERGY: 20, GAS: 5 },
    cost: { METAL: 800, CRYSTAL: 400 },
    description: 'Forges high-grade military alloys for ship and turret upgrades.',
  },
  {
    name: 'Strategic Command',
    type: 'TACTICAL',
    category: 'COMMAND',
    level: 1,
    consumption: { ENERGY: 40 },
    cost: { METAL: 2000, CRYSTAL: 800, DARK_MATTER: 10 },
    description: 'Increases the maximum military rank and coordinates regional defense.',
    automation: 5,
  },
];

export const INITIAL_TECHNOLOGIES: Technology[] = [
  {
    id: 'neural-drone-swarm',
    name: 'Neural Drone Swarm',
    category: 'AI',
    rarity: 'UNCOMMON',
    cost: { METAL: 350, CRYSTAL: 90, ENERGY: 200 },
    benefits: ['+2 autonomous drones', '+10% mining output while online or offline'],
    risks: ['Small chance of AI corruption events at high threat levels'],
    dependencies: [],
    unlocked: false,
    progress: 0,
  },
  {
    id: 'gravity-harvester',
    name: 'Gravity Harvester',
    category: 'INDUSTRIAL',
    rarity: 'RARE',
    cost: { METAL: 800, CRYSTAL: 250, GAS: 120 },
    benefits: ['Unlocks passive dark matter trickle', 'Improves wormhole stability'],
    risks: ['Can attract plasma worms during storms'],
    dependencies: ['neural-drone-swarm'],
    unlocked: false,
    progress: 0,
  },
  {
    id: 'quantum-shield-mesh',
    name: 'Quantum Shield Mesh',
    category: 'MILITARY',
    rarity: 'EPIC',
    cost: { ENERGY: 1000, CRYSTAL: 420, QUANTUM_DUST: 35 },
    benefits: ['+80 colony shields', 'Shared raid mitigation over LAN sync'],
    risks: ['Consumes emergency reserves when overloaded'],
    dependencies: ['gravity-harvester'],
    unlocked: false,
    progress: 0,
  },
  {
    id: 'alien-alloy-synthesis',
    name: 'Alien Alloy Synthesis',
    category: 'ESOTERIC',
    rarity: 'RARE',
    cost: { ALIEN_BIOMASS: 50, CRYSTAL: 300, METAL: 1000 },
    benefits: ['Increases building max health by 25%', 'Unlocks Plasma Foundry upgrades'],
    risks: ['Organic contamination of metal stores'],
    dependencies: [],
    unlocked: false,
    progress: 0,
  },
];
