import type { Building, Technology } from '../schemas/game';

export const INITIAL_BUILDINGS: Building[] = [
  {
    id: 'colony-core-001',
    name: 'Colony Core',
    type: 'COMMAND',
    category: 'COMMAND',
    level: 1,
    production: { ENERGY: 5 },
    cost: { METAL: 0 },
    description: 'Autonomous command spine for the first planetary outpost.',
    automation: 1,
    maxHealth: 1000,
    currentHealth: 1000,
    efficiency: 1,
  },
  {
    id: 'solar-hub-001',
    name: 'Solar Hub',
    type: 'ENERGY_GENERATOR',
    category: 'PRODUCTION',
    level: 1,
    production: { ENERGY: 15 },
    cost: { METAL: 50 },
    description: 'Basic energy generation using orbital solar arrays.',
    efficiency: 1,
  },
];

export const BUILDING_TEMPLATES: Omit<Building, 'id'>[] = [
  {
    name: 'Solar Hub',
    type: 'ENERGY_GENERATOR',
    category: 'PRODUCTION',
    level: 1,
    production: { ENERGY: 15 },
    cost: { METAL: 50 },
    description: 'Basic energy generation using solar arrays.',
    efficiency: 1,
  },
  {
    name: 'Mining Station',
    type: 'METAL_EXTRACTOR',
    category: 'PRODUCTION',
    level: 1,
    production: { METAL: 8 },
    consumption: { ENERGY: 3 },
    cost: { METAL: 100, ENERGY: 20 },
    description: 'Extracts metal from the planet surface.',
    automation: 1,
    efficiency: 1,
  },
  {
    name: 'Storage Vault',
    type: 'STORAGE',
    category: 'STORAGE',
    level: 1,
    cost: { METAL: 150, CRYSTAL: 30 },
    description: 'Increases maximum resource storage capacity.',
    efficiency: 1,
  },
  {
    name: 'Defense Battery',
    type: 'DEFENSE',
    category: 'DEFENSE',
    level: 1,
    consumption: { ENERGY: 4 },
    cost: { METAL: 250, ENERGY: 100 },
    description: 'Plasma-based defense battery to ward off pirates.',
    defense: 25,
    attack: 10,
    armor: 5,
    efficiency: 1,
  },
  {
    name: 'Fighter Hangar',
    type: 'UNIT_PRODUCTION',
    category: 'MILITARY',
    level: 1,
    consumption: { ENERGY: 10 },
    cost: { METAL: 500, CRYSTAL: 200 },
    description: 'Produces and maintains space superiority fighters.',
    efficiency: 1,
  },
];

export const INITIAL_TECHNOLOGIES: Technology[] = [
  {
    id: 'basic-automation',
    name: 'Basic Automation',
    category: 'INDUSTRIAL',
    rarity: 'COMMON',
    cost: { METAL: 100, ENERGY: 50 },
    benefits: ['+10% efficiency for all production buildings'],
    risks: [],
    dependencies: [],
    unlocked: false,
    progress: 0,
  },
  {
    id: 'plasma-shields',
    name: 'Plasma Shields',
    category: 'MILITARY',
    rarity: 'UNCOMMON',
    cost: { METAL: 400, CRYSTAL: 300, ENERGY: 500 },
    benefits: ['Unlocks high-capacity shield generators', '+20% shield max'],
    risks: [],
    dependencies: [],
    unlocked: false,
    progress: 0,
  },
];
